export type Category =
  | 'Packs'
  | 'Beauté'
  | 'Cheveux'
  | 'Nutrition'
  | 'Fitness & Minceur'
  | 'Sonya'
  | 'Infinite'
  | "Pulpe d'Aloe Vera"
  | 'Produits de la Ruche'

export interface Product {
  id: string
  slug: string
  name: string
  category: Category
  price: number
  rating: number
  reviewCount: number
  tagline: string
  description: string
  ingredients: string[]
  howToUse: string
  image: string
  gallery?: string[]
  size?: string
  bestSeller?: boolean
  new?: boolean
  packContents?: string[]
  // null/undefined = stock not tracked (always available); 0 = out of stock.
  stock?: number | null
  nameAr?: string
  taglineAr?: string
  descriptionAr?: string
  ingredientsAr?: string[]
  howToUseAr?: string
}

export type StockStatus = 'untracked' | 'out' | 'low' | 'in'

export function stockStatus(stock?: number | null): StockStatus {
  if (stock === null || stock === undefined) return 'untracked'
  if (stock <= 0) return 'out'
  if (stock <= 5) return 'low'
  return 'in'
}

export const products: Product[] = [
  // ---------- Pulpe d'Aloe Vera ----------
  {
    id: 'p01',
    slug: 'aloe-vera-gel-330ml',
    name: 'Forever Aloe Vera Gel 330ml',
    nameAr: 'جل ألوفيرا فوريفر 330 مل',
    category: "Pulpe d'Aloe Vera",
    price: 7,
    rating: 4.9,
    reviewCount: 412,
    tagline: "Notre produit signature, désormais sans conservateur et riche en vitamine C.",
    taglineAr: 'المنتج المميز، الآن بدون مواد حافظة وغني بفيتامين سي.',
    description:
      "L'Aloe Vera Forever fait peau neuve ! Riche d'un savoir-faire de 40 ans, Forever a revisité son produit signature et créé une toute nouvelle version sans conservateur et riche en vitamine C, dans un emballage 100% recyclable. Le secret : 99,7% de gel d'Aloe vera et une dose synergique de vitamine C.",
    descriptionAr:
      "تجدد ألوفيرا فوريفر مظهره! بفضل خبرة 40 عاماً، أعادت فوريفر تصميم منتجها المميز وابتكرت نسخة جديدة كلياً بدون مواد حافظة وغنية بفيتامين سي، في عبوة قابلة لإعادة التدوير بنسبة 100%. السر: 99.7% جل ألوفيرا وجرعة تآزرية من فيتامين سي.",
    ingredients: ["99,7% de gel d'Aloe vera", 'Vitamine C'],
    ingredientsAr: ['99.7% جل ألوفيرا', 'فيتامين سي'],
    howToUse: '30 à 40 ml, 3 fois par jour.',
    howToUseAr: '30 إلى 40 مل، 3 مرات يومياً.',
    image: '/products/p01-aloe-vera-gel.png',
    size: '330 ml',
    bestSeller: true,
  },
  {
    id: 'p02',
    slug: 'aloe-peche-330ml',
    name: 'Forever Aloe Pêche 330ml',
    nameAr: 'ألوفيرا بالخوخ فوريفر 330 مل',
    category: "Pulpe d'Aloe Vera",
    price: 7,
    rating: 4.7,
    reviewCount: 188,
    tagline: 'Aloe vera, purée de pêche naturelle et vitamine C pour une saveur douce et savoureuse.',
    taglineAr: 'ألوفيرا، هريس الخوخ الطبيعي وفيتامين سي بنكهة لذيذة وناعمة.',
    description:
      "La nouvelle formule de l'Aloe Pêche associe de l'Aloe vera (84,5%), de la purée de pêche et du jus concentré de raisin blanc pour une saveur douce, ainsi qu'une dose synergique de vitamine C. Packaging 100% recyclable.",
    ingredients: ["84,5% de pulpe d'Aloe vera", 'Purée de pêche naturelle', 'Jus concentré de raisin blanc', 'Arôme pêche'],
    howToUse: '30 à 40 ml, 3 fois par jour.',
    image: '/products/p02-aloe-peche.png',
    size: '330 ml',
  },
  {
    id: 'p03',
    slug: 'aloe-berry-nectar-330ml',
    name: 'Forever Aloe Berry Nectar 330ml',
    nameAr: 'ألوفيرا بيري نكتار فوريفر 330 مل',
    category: "Pulpe d'Aloe Vera",
    price: 7,
    rating: 4.8,
    reviewCount: 203,
    tagline: "Une large dose de pulpe d'Aloe vera, jus de pomme et canneberge, sans conservateur.",
    taglineAr: 'جرعة كبيرة من لب الألوفيرا، عصير التفاح والتوت البري، بدون مواد حافظة.',
    description:
      "Une large dose (90,7%) de pulpe d'Aloe vera, un soupçon de jus de pomme et de canneberge, de la vitamine C, aucun conservateur et un emballage 100% recyclable.",
    ingredients: ["90,7% de pulpe d'Aloe vera", 'Jus concentré de pomme', 'Jus concentré de canneberge'],
    howToUse: '30 à 40 ml, 3 fois par jour.',
    image: '/products/p03-aloe-berry-nectar.png',
    size: '330 ml',
  },
  {
    id: 'p04',
    slug: 'aloe-mangue-1l',
    name: 'Forever Aloe Mangue',
    nameAr: 'ألوفيرا مانجو فوريفر',
    category: "Pulpe d'Aloe Vera",
    price: 38,
    rating: 4.8,
    reviewCount: 96,
    tagline: 'Gel Aloe vera et purée de mangue naturelle pour un boost de nutrition et de saveur.',
    taglineAr: 'جل ألوفيرا وهريس مانجو طبيعي لدفعة إضافية من التغذية والنكهة.',
    description:
      "Avec ses 86% de gel d'Aloe vera et sa purée de mangue naturelle, cette nouvelle déclinaison apporte un boost supplémentaire de nutrition et de saveur. Sans conservateurs, source de vitamine C.",
    ingredients: ["86% de gel d'Aloe vera pur", 'Vitamine C', 'Concentré de purée de mangue'],
    howToUse: 'Secouer légèrement avant de servir — 30 à 40 ml dilués dans 240 ml d\'eau ou de jus de fruit, 3 fois par jour.',
    image: '/products/page-08.jpg',
    size: '1 litre',
    new: true,
  },
  {
    id: 'p05',
    slug: 'aloe-berry-nectar-1l',
    name: 'Aloe Berry Nectar 1L',
    nameAr: 'ألوفيرا بيري نكتار 1 لتر',
    category: "Pulpe d'Aloe Vera",
    price: 38,
    rating: 4.7,
    reviewCount: 121,
    tagline: 'Goût acidulé, extrait de canneberge et pulpe Aloe Vera riche en antioxydants.',
    taglineAr: 'طعم منعش، مستخلص التوت البري ولب الألوفيرا الغني بمضادات الأكسدة.',
    description:
      "Au goût délicieusement acidulé, l'Aloe Berry Nectar contient de l'extrait de canneberge associé à la pulpe d'Aloe Vera. La plante contribue aux défenses naturelles de l'organisme.",
    ingredients: ["90,6% de pulpe d'Aloe vera stabilisée", "1,71% d'extraits de canneberge et de pomme"],
    howToUse: '30 à 40 ml par jour, 3 fois par jour soit entre 90 et 120 ml par jour.',
    image: '/products/page-09.jpg',
    size: '1 litre',
  },
  {
    id: 'p06',
    slug: 'pulpe-aloe-vera-stabilisee-1l',
    name: "Pulpe d'Aloe Vera Stabilisée",
    nameAr: 'لب الألوفيرا المثبت',
    category: "Pulpe d'Aloe Vera",
    price: 38,
    rating: 4.9,
    reviewCount: 267,
    tagline: "Le produit à utiliser quotidiennement pour conserver un bien-être optimal.",
    taglineAr: 'المنتج الذي يُستخدم يومياً للحفاظ على عافية مثالية.',
    description:
      "La pulpe d'Aloès stabilisée est le produit à utiliser quotidiennement pour conserver un bien-être optimal. L'Aloe vera contribue au maintien du système immunitaire et possède de puissants antioxydants.",
    descriptionAr:
      'لب الألوة المثبت هو المنتج الذي يُستخدم يومياً للحفاظ على عافية مثالية. تساهم الألوفيرا في دعم الجهاز المناعي وتحتوي على مضادات أكسدة قوية.',
    ingredients: ["96,2% de pulpe d'Aloe vera stabilisée"],
    ingredientsAr: ['96.2% لب ألوفيرا مثبت'],
    howToUse: '30 à 40 ml par jour, 3 fois par jour soit entre 90 et 120 ml par jour.',
    howToUseAr: '30 إلى 40 مل يومياً، 3 مرات يومياً أي ما بين 90 و120 مل يومياً.',
    image: '/products/page-09.jpg',
    size: '1 litre',
    bestSeller: true,
  },
  {
    id: 'p07',
    slug: 'aloe-bits-n-peaches-1l',
    name: "Forever Aloe Bits N' Peaches",
    nameAr: 'ألوفيرا بيتس آند بيتشز فوريفر',
    category: "Pulpe d'Aloe Vera",
    price: 38,
    rating: 4.6,
    reviewCount: 84,
    tagline: 'Cœur d\'Aloès enrichi en concentré de jus de pêche, savoureux et doux.',
    taglineAr: 'قلب الألوة المُخصّب بمركز عصير الخوخ، لذيذ وناعم.',
    description:
      "Savoureux et doux, le Cœur d'Aloès est enrichi en concentré de jus de pêche. L'Aloe Vera aide à stimuler le métabolisme et contribue aux défenses naturelles de l'organisme.",
    ingredients: ["91,17% de pulpe d'Aloe Vera stabilisée", '0,1% de concentré de jus de pêche'],
    howToUse: '30 à 40 ml par jour, 3 fois par jour soit entre 90 et 120 ml par jour.',
    image: '/products/page-09.jpg',
    size: '1 litre',
  },

  // ---------- Produits de la Ruche ----------
  {
    id: 'p08',
    slug: 'forever-bee-honey',
    name: 'Forever Bee Honey',
    nameAr: 'عسل النحل فوريفر',
    category: 'Produits de la Ruche',
    price: 22,
    rating: 4.8,
    reviewCount: 156,
    tagline: '« L\'or de la ruche », produit par les abeilles à partir du nectar des fleurs.',
    taglineAr: '«ذهب الخلية»، ينتجه النحل من رحيق الأزهار.',
    description:
      "Le miel aussi appelé « or de la ruche » est produit par les abeilles à partir du nectar des fleurs. Avec sa texture fluide, le Forever Bee Honey s'ajoute facilement à l'alimentation. Son flacon est facile à utiliser pour doser.",
    ingredients: ['100% miel naturel'],
    howToUse: 'Pour une consommation personnelle. Enfants : à consommer à partir de 12 mois.',
    image: '/products/page-10.jpg',
    size: '500 g',
  },
  {
    id: 'p09',
    slug: 'forever-propolis',
    name: 'Forever Propolis',
    nameAr: 'بروبوليس فوريفر',
    category: 'Produits de la Ruche',
    price: 24,
    rating: 4.6,
    reviewCount: 73,
    tagline: 'Résine collectée par les abeilles, aux propriétés antimicrobiennes.',
    taglineAr: 'راتينج يجمعه النحل، بخصائص مضادة للميكروبات.',
    description:
      "La propolis est une résine collectée et métabolisée par les abeilles mellifères à partir des arbres. Cette substance aux propriétés antimicrobiennes est utilisée pour protéger la ruche de la prolifération de champignons et de bactéries.",
    ingredients: ['69,6% de poudre de propolis', '7% de miel', 'Contient soja et amande'],
    howToUse: 'Prendre 2 comprimés par jour.',
    image: '/products/page-11.jpg',
    size: '60 comprimés',
  },
  {
    id: 'p10',
    slug: 'forever-bee-pollen',
    name: 'Forever Bee Pollen',
    nameAr: 'حبوب لقاح النحل فوريفر',
    category: 'Produits de la Ruche',
    price: 22,
    rating: 4.7,
    reviewCount: 91,
    tagline: 'Collecté sur les fleurs, améliore la vitalité lors des changements de saison.',
    taglineAr: 'يُجمع من الأزهار، يحسّن الحيوية عند تغير الفصول.',
    description:
      "Collecté sur les fleurs par les abeilles, le Pollen Forever améliore la vitalité et la résistance de l'organisme lors des changements de saison.",
    ingredients: ['86% pollen (500 mg par comprimé)', '12% miel'],
    howToUse: '3 comprimés par jour pendant les repas.',
    image: '/products/page-11.jpg',
    size: '100 comprimés',
  },
  {
    id: 'p11',
    slug: 'forever-royal-jelly',
    name: 'Forever Royal Jelly',
    nameAr: 'الغذاء الملكي فوريفر',
    category: 'Produits de la Ruche',
    price: 28,
    rating: 4.8,
    reviewCount: 110,
    tagline: 'Idéale pour se prémunir contre les conséquences de la période hivernale.',
    taglineAr: 'مثالي للوقاية من تداعيات فصل الشتاء.',
    description:
      "La Gelée Royale est idéale pour se prémunir contre les conséquences de la période hivernale. Forever Royal Jelly renforce en douceur les défenses naturelles de l'organisme.",
    ingredients: ['75,8 mg de gelée royale lyophilisée (équivalent à 250 mg de gelée royale fraîche par comprimé)'],
    howToUse: 'Prendre 1 à 2 comprimés à croquer par jour.',
    image: '/products/page-11.jpg',
    size: '60 comprimés',
  },

  // ---------- Nutrition ----------
  {
    id: 'p12',
    slug: 'forever-active-pro-b',
    name: 'Forever Active Pro-B',
    nameAr: 'أكتيف برو-بي فوريفر',
    category: 'Nutrition',
    price: 32,
    rating: 4.8,
    reviewCount: 245,
    tagline: 'Probiotiques et prébiotiques pour un coup de pouce à la flore intestinale.',
    taglineAr: 'بروبيوتيك وبريبايوتيك لدعم فلورا الأمعاء.',
    description:
      "La flore intestinale est composée de plusieurs milliards de bactéries qui participent au bon fonctionnement de l'organisme. Forever Active Pro-B associe de façon synergique des probiotiques et des prébiotiques.",
    descriptionAr:
      'تتكون فلورا الأمعاء من مليارات البكتيريا التي تساهم في حسن سير عمل الجسم. يجمع Forever Active Pro-B بشكل تآزري بين البروبيوتيك والبريبايوتيك.',
    ingredients: ['Probiotiques', 'Prébiotiques'],
    ingredientsAr: ['بروبيوتيك', 'بريبايوتيك'],
    howToUse: 'Prendre 1 gélule par jour avec un verre d\'eau, 30 minutes avant le repas.',
    howToUseAr: 'تناول كبسولة واحدة يومياً مع كوب ماء، قبل 30 دقيقة من الوجبة.',
    image: '/products/page-12.jpg',
    size: '30 capsules',
    bestSeller: true,
  },
  {
    id: 'p13',
    slug: 'forever-kids',
    name: 'Forever Kids',
    nameAr: 'فوريفر كيدز',
    category: 'Nutrition',
    price: 26,
    rating: 4.7,
    reviewCount: 102,
    tagline: '12 vitamines et 2 minéraux pour le développement de l\'enfant.',
    taglineAr: '12 فيتاميناً ومعدنين لنمو الطفل.',
    description:
      "Forever Kids contient 12 vitamines (A, B, C, D, E) et 2 minéraux (fer, zinc). Cette association contribue au fonctionnement normal du système immunitaire, réduit la fatigue et favorise le développement cognitif.",
    ingredients: ['12 vitamines', 'Fer', 'Zinc'],
    howToUse: 'Enfants à partir de 4 ans et jeunes adultes : 4 comprimés à croquer par jour.',
    image: '/products/page-13.jpg',
    size: '48 comprimés',
  },
  {
    id: 'p14',
    slug: 'fields-of-greens',
    name: 'Fields of Greens',
    nameAr: 'فيلدز أوف جرينز',
    category: 'Nutrition',
    price: 30,
    rating: 4.5,
    reviewCount: 68,
    tagline: 'Jeunes pousses végétales : orge, blé, luzerne et piments de Cayenne.',
    taglineAr: 'براعم نباتية فتية: الشعير، القمح، الجلبان وفلفل الكايين.',
    description:
      "Fields of Greens est obtenu à partir de jeunes pousses végétales : feuilles d'orge, de blé, de luzerne et de piments de Cayenne.",
    ingredients: ["19% poudre de feuilles d'orge", '19% poudre de pousse de blé', '19% poudre de feuilles de luzerne', '0,2% poudre de piments de Cayenne'],
    howToUse: 'Prendre 2 comprimés par jour.',
    image: '/products/page-13.jpg',
    size: '68 comprimés',
  },
  {
    id: 'p15',
    slug: 'forever-absorbent-c',
    name: 'Forever Absorbent-C',
    nameAr: 'أبسوربنت-سي فوريفر',
    category: 'Nutrition',
    price: 24,
    rating: 4.7,
    reviewCount: 178,
    tagline: 'Vitamine C pour réduire la fatigue et renforcer la résistance de l\'organisme.',
    taglineAr: 'فيتامين سي لتقليل التعب وتقوية مقاومة الجسم.',
    description:
      "La vitamine C contribue à réduire la fatigue et permet de retrouver tonus et énergie. Elle est indispensable pour renforcer la résistance de l'organisme.",
    ingredients: ["42% de fibres naturelles d'avoine", "5,2% d'acide ascorbique (vitamine C)", '9,5% de miel'],
    howToUse: '1 comprimé à croquer par jour, le matin.',
    image: '/products/page-13.png',
    size: '100 comprimés',
  },
  {
    id: 'p16',
    slug: 'forever-ivision',
    name: 'Forever iVision',
    nameAr: 'آي فيجن فوريفر',
    category: 'Nutrition',
    price: 34,
    rating: 4.6,
    reviewCount: 59,
    tagline: 'Vitamines A, C, E et zinc pour protéger les yeux face aux écrans.',
    taglineAr: 'فيتامينات A وC وE والزنك لحماية العينين من الشاشات.',
    description:
      "Adaptez vos yeux à un style de vie connecté ! Forever iVision est le complément alimentaire pour notre vision avec un apport complet de vitamines A, C, E et de zinc.",
    ingredients: ['Vitamines A, C, E', 'Zinc', 'Lutemax 2020', 'Contient soja et poisson'],
    howToUse: "Prendre 2 capsules par jour avec un demi-verre d'eau. Déconseillé aux fumeurs (bêta-carotène).",
    image: '/products/page-14.jpg',
    size: '60 comprimés',
  },
  {
    id: 'p17',
    slug: 'forever-supergreens',
    name: 'Forever Supergreens',
    nameAr: 'سوبر جرينز فوريفر',
    category: 'Nutrition',
    price: 36,
    rating: 4.6,
    reviewCount: 77,
    tagline: 'Plus de 20 variétés de fruits et légumes, Aloe vera, vitamine C et magnésium.',
    taglineAr: 'أكثر من 20 نوعاً من الفواكه والخضار، ألوفيرا، فيتامين سي والمغنيسيوم.',
    description:
      "Forever Supergreens contient plus de 20 variétés de fruits et légumes, de l'Aloe vera, de la vitamine C et du magnésium. Ce mélange favorise le maintien des défenses naturelles et la récupération musculaire.",
    ingredients: ['Pomme', 'Betterave', 'Tomate', 'Citrouille', 'Carotte', 'Épinards', 'Brocolis', 'Aloe vera', 'Chou Kale', 'Thé vert', 'Baies de Goji'],
    howToUse: "Verser un stick dans votre boisson à l'Aloe Vera préférée ou dans de l'eau, mélanger et boire.",
    image: '/products/page-14.jpg',
    size: '30 sachets',
  },
  {
    id: 'p18',
    slug: 'forever-immublend',
    name: 'Forever ImmuBlend',
    nameAr: 'إيميوبلند فوريفر',
    category: 'Nutrition',
    price: 33,
    rating: 4.7,
    reviewCount: 94,
    tagline: 'Vitamines, minéraux et champignons traditionnels pour stimuler l\'immunité.',
    taglineAr: 'فيتامينات ومعادن وفطريات تقليدية لتحفيز المناعة.',
    description:
      "Forever ImmuBlend, association de vitamines, minéraux et de champignons traditionnellement utilisés en Asie, contribue à stimuler les défenses immunitaires pour optimiser son capital santé.",
    ingredients: ['Mélange de champignons', 'Vitamines C, D3', 'Zinc'],
    howToUse: 'Prendre 1 comprimé par jour.',
    image: '/products/page-15.jpg',
    size: '60 capsules',
  },
  {
    id: 'p19',
    slug: 'forever-daily',
    name: 'Forever Daily',
    nameAr: 'فوريفر ديلي',
    category: 'Nutrition',
    price: 40,
    rating: 4.8,
    reviewCount: 134,
    tagline: 'Formule exclusive de 55 ingrédients pour un bien-être optimal au quotidien.',
    taglineAr: 'تركيبة حصرية من 55 مكوناً لعافية مثالية يومياً.',
    description:
      "Formule exclusive de 55 ingrédients qui associe les nutriments du Complexe AOS (Aloe OligoSaccharides) à des vitamines, minéraux et phytonutriments d'extraits de fruits et légumes.",
    ingredients: ['Complexe AOS', '12 vitamines (A, B1, B2, B3, B5, B6, B8, B9, B12, C, D, E)', '8 minéraux essentiels', 'Forever FVX20 (20 extraits de fruits et légumes)'],
    howToUse: 'Prendre 2 comprimés tous les matins.',
    image: '/products/page-16.jpg',
    size: '60 comprimés',
  },
  {
    id: 'p20',
    slug: 'forever-ail-thym',
    name: 'Forever Ail et Thym',
    nameAr: 'الثوم والزعتر فوريفر',
    category: 'Nutrition',
    price: 22,
    rating: 4.5,
    reviewCount: 52,
    tagline: 'Combinaison unique de 2 extraits de plantes pour le confort digestif.',
    taglineAr: 'مزيج فريد من مستخلصين نباتيين للراحة الهضمية.',
    description:
      "Forever Ail et Thym est une combinaison unique de 2 extraits de plantes connues pour améliorer le confort digestif. Capsule sans odeur équivalent à 1000 mg d'ail frais.",
    ingredients: ["3% d'extrait de bulbe d'ail", '15,4% poudre de thym (feuilles)', 'Contient du soja'],
    howToUse: 'Prendre 1 capsule 3 fois par jour, de préférence pendant les repas.',
    image: '/products/page-16.jpg',
    size: '100 comprimés',
  },
  {
    id: 'p21',
    slug: 'forever-fiber',
    name: 'Forever Fiber',
    nameAr: 'فايبر فوريفر',
    category: 'Nutrition',
    price: 28,
    rating: 4.6,
    reviewCount: 65,
    tagline: '5g de fibres hydrosolubles pour stimuler les fonctions intestinales.',
    taglineAr: '5 غ من الألياف الذائبة في الماء لتحفيز وظائف الأمعاء.',
    description:
      "Forever Fiber apporte 5g de fibres hydrosolubles pour stimuler les fonctions intestinales et retrouver un bon confort digestif.",
    ingredients: ['5 g de fibres solubles'],
    howToUse: "Prendre 1 sachet tous les matins, à diluer dans de l'eau ou avec de la pulpe stabilisée.",
    image: '/products/page-17.jpg',
    size: '30 sachets de 6,1 g',
  },
  {
    id: 'p22',
    slug: 'infusion-fleur-aloes',
    name: "Infusion Fleur d'Aloès",
    nameAr: 'منقوع زهرة الألوة',
    category: 'Nutrition',
    price: 18,
    rating: 4.6,
    reviewCount: 48,
    tagline: 'Écorce d\'orange, zeste de citron, cannelle et clou de girofle.',
    taglineAr: 'قشر البرتقال، قشر الليمون، القرفة والقرنفل.',
    description:
      "Cette infusion à l'arôme subtil et délicat associe les goûts acidulés de l'écorce d'orange et de zeste de citron, les saveurs épicées de la cannelle et du clou de girofle. Apporte un bien-être digestif.",
    ingredients: ["Cannelle", "Zestes d'orange", 'Clous de girofle', 'Feuilles de mûrier', 'Poivre de Jamaïque', 'Fleur d\'aloès', 'Camomille'],
    howToUse: 'Laisser infuser 1 sachet dans environ 1 litre d\'eau.',
    image: '/products/page-17.jpg',
    size: '25 sachets',
  },
  {
    id: 'p23',
    slug: 'vitolize-femmes',
    name: 'Vitolize Femmes',
    nameAr: 'فيتولايز للنساء',
    category: 'Nutrition',
    price: 36,
    rating: 4.6,
    reviewCount: 71,
    tagline: 'Plantes, vitamines et minéraux conçus spécialement pour les femmes.',
    taglineAr: 'نباتات وفيتامينات ومعادن مصممة خصيصاً للنساء.',
    description:
      "Ce mélange naturel de plantes, vitamines et minéraux a été spécialement conçu pour les femmes. La vitamine B6 aide à réguler l'équilibre hormonal et la passiflore aide à diminuer le stress.",
    ingredients: ['Poudre de pomme', 'Baies de Schisandra', 'Poudre de fruits de canneberge', 'Magnésium', 'Vitamines C, D, B12'],
    howToUse: '4 capsules par jour.',
    image: '/products/page-18.jpg',
    size: '60 capsules',
  },
  {
    id: 'p24',
    slug: 'vitolize-hommes',
    name: 'Vitolize Hommes',
    nameAr: 'فيتولايز للرجال',
    category: 'Nutrition',
    price: 38,
    rating: 4.6,
    reviewCount: 64,
    tagline: 'Vitamines, minéraux et phytostérols pour le bon fonctionnement de la prostate.',
    taglineAr: 'فيتامينات ومعادن وفيتوستيرول لدعم البروستاتا.',
    description:
      "Vitolize Hommes contient des vitamines et des minéraux, ainsi que des phytostérols pour conserver un bon fonctionnement de la prostate. Le zinc contribue au maintien normal de la fertilité.",
    ingredients: ['Huile de pépins de citrouille', 'Vitamines B6, C, D, E', 'Zinc', 'Sélénium', 'Contient soja et poisson'],
    howToUse: '2 capsules par jour.',
    image: '/products/page-18.jpg',
    size: '120 capsules',
  },
  {
    id: 'p25',
    slug: 'forever-move',
    name: 'Forever Move',
    nameAr: 'فوريفر موف',
    category: 'Nutrition',
    price: 42,
    rating: 4.7,
    reviewCount: 88,
    tagline: 'Membrane de coquille d\'œuf NEM® et curcuma BioCurc® pour le confort articulaire.',
    taglineAr: 'غشاء قشر البيض NEM® وكركم BioCurc® لراحة المفاصل.',
    description:
      "Forever Move est l'association de deux ingrédients brevetés, la membrane de coquille d'œuf NEM® et le curcuma BioCurc®. Ils agissent en synergie pour favoriser un confort articulaire optimal.",
    ingredients: ["Membrane de coquille d'œuf NEM®", 'Extrait de rhizome de curcuma BioCurc®'],
    howToUse: 'Prendre 3 capsules par jour.',
    image: '/products/page-19.jpg',
    size: '90 capsules',
  },
  {
    id: 'p26',
    slug: 'forever-calcium',
    name: 'Forever Calcium',
    nameAr: 'كالسيوم فوريفر',
    category: 'Nutrition',
    price: 26,
    rating: 4.6,
    reviewCount: 57,
    tagline: 'Calcium, magnésium et vitamines pour une ossature normale.',
    taglineAr: 'كالسيوم ومغنيسيوم وفيتامينات لعظام طبيعية.',
    description:
      "Forever Calcium contient des vitamines C et D ainsi que des minéraux (calcium, magnésium, manganèse, zinc, cuivre) pour contribuer au maintien d'une ossature et d'une fonction musculaire normales.",
    ingredients: ['Calcium', 'Magnésium', 'Vitamine C', 'Zinc', 'Manganèse', 'Cuivre', 'Vitamine D'],
    howToUse: '4 comprimés par jour.',
    image: '/products/page-20.jpg',
    size: '376 comprimés',
  },
  {
    id: 'p27',
    slug: 'forever-arctic-sea',
    name: 'Forever Arctic-Sea',
    nameAr: 'آركتيك-سي فوريفر',
    category: 'Nutrition',
    price: 40,
    rating: 4.8,
    reviewCount: 142,
    tagline: 'Oméga-3 (EPA et DHA) pour le fonctionnement normal du cerveau et du cœur.',
    taglineAr: 'أوميغا-3 (EPA وDHA) لوظيفة طبيعية للدماغ والقلب.',
    description:
      "Forever Arctic-Sea contient des acides gras insaturés, des oméga-3, dont de l'EPA et du DHA présents dans les huiles de poissons et de calamar. Ils contribuent au fonctionnement normal du cerveau et du cœur.",
    descriptionAr:
      'يحتوي Forever Arctic-Sea على أحماض دهنية غير مشبعة، أوميغا-3، بما في ذلك EPA وDHA الموجودة في زيوت الأسماك والحبار. تساهم في الوظيفة الطبيعية للدماغ والقلب.',
    ingredients: ['45,9% huile de poissons', '16,6% huile de calamar', '11,3% huile d\'olive extravierge', 'Contient du poisson'],
    ingredientsAr: ['45.9% زيت السمك', '16.6% زيت الحبار', '11.3% زيت زيتون بكر ممتاز', 'يحتوي على السمك'],
    howToUse: 'Prendre 2 capsules 3 fois par jour, soit 6 capsules par jour.',
    howToUseAr: 'تناول كبسولتين 3 مرات يومياً، أي 6 كبسولات في اليوم.',
    image: '/products/page-20.jpg',
    size: '90 capsules',
    bestSeller: true,
  },
  {
    id: 'p28',
    slug: 'aloe-msm-gel',
    name: 'Aloe MSM Gel',
    nameAr: 'جل الألوفيرا إم إس إم',
    category: 'Nutrition',
    price: 25,
    rating: 4.7,
    reviewCount: 99,
    tagline: 'Soufre organique pour favoriser le maintien du tissu conjonctif.',
    taglineAr: 'كبريت عضوي لدعم النسيج الضام.',
    description:
      "Le methyl sulfonyl méthane (MSM) est une source stable et naturelle de soufre organique, présent en concentration élevée dans les articulations, favorisant le maintien de l'intégrité du tissu conjonctif.",
    descriptionAr:
      'الميثيل سلفونيل ميثان (MSM) مصدر مستقر وطبيعي للكبريت العضوي، موجود بتركيز عالٍ في المفاصل، ويساهم في الحفاظ على سلامة النسيج الضام.',
    ingredients: ["Gel d'aloès", '15% de MSM'],
    ingredientsAr: ['جل الألوة', '15% MSM'],
    howToUse: 'Appliquer en massages généreux sur les zones nécessaires.',
    howToUseAr: 'يُطبق بتدليك سخي على المناطق المطلوبة.',
    image: '/products/page-21.jpg',
    size: '118 ml',
    bestSeller: true,
  },
  {
    id: 'p29',
    slug: 'emulsion-thermogene',
    name: 'Émulsion Thermogène',
    nameAr: 'مستحلب التدفئة',
    category: 'Nutrition',
    price: 27,
    rating: 4.5,
    reviewCount: 46,
    tagline: 'Crème de massage au menthol pour soulager les articulations.',
    taglineAr: 'كريم تدليك بالمنثول لتخفيف آلام المفاصل.',
    description:
      "Cette crème de massage est le complément idéal pour soulager les articulations ou préparer les muscles à l'effort grâce au menthol et aux huiles d'eucalyptus, de sésame, de jojoba et d'abricot.",
    ingredients: ['35,9% menthol et huiles essentielles'],
    howToUse: 'Appliquer en massages. Ne pas appliquer sur le visage.',
    image: '/products/page-21.jpg',
    size: '118 ml',
  },
  {
    id: 'p30',
    slug: 'forever-argi-plus',
    name: 'Forever Argi+',
    nameAr: 'أرجي+ فوريفر',
    category: 'Nutrition',
    price: 44,
    rating: 4.7,
    reviewCount: 103,
    tagline: 'L-Arginine et cocktail de vitamines pour l\'effort extrême.',
    taglineAr: 'أل-أرجينين ومزيج فيتامينات للمجهود الشديد.',
    description:
      "Vitalité, force, endurance, sport extrême : Forever Argi+ combine la L-Arginine à un cocktail unique de vitamines et d'extraits de fruits pour un accompagnement idéal pendant l'effort.",
    ingredients: ['51% de L-Arginine', "Mélange d'extraits de fruits rouges", 'Vitamines C, B6, B9'],
    howToUse: 'Mélanger une dosette à 240 ml de boisson (eau, jus de fruits ou Pulpe d\'Aloe Vera).',
    image: '/products/page-22.jpg',
    size: '30 sachets de 10 g',
  },

  // ---------- Fitness & Minceur ----------
  {
    id: 'p31',
    slug: 'forever-lean',
    name: 'Forever Lean',
    nameAr: 'فوريفر لين',
    category: 'Fitness & Minceur',
    price: 39,
    rating: 4.6,
    reviewCount: 87,
    tagline: 'Fibres de cactus Opuntia pour aider à contrôler le poids.',
    taglineAr: 'ألياف الصبار أوبونتيا للمساعدة في التحكم بالوزن.',
    description:
      "Les fibres extraites du cactus Opuntia ficus-indica ont la capacité d'attirer et retenir les graisses et les sucres. Les graines de haricots blancs et le chrome aident à réduire l'apport calorique journalier.",
    ingredients: ['Feuilles de Neopuntia®', 'Extrait de graines de haricot sec', 'Chrome'],
    howToUse: 'Prendre 1 capsule avec un verre d\'eau avant le repas. Jusqu\'à 4 capsules par jour.',
    image: '/products/page-23.jpg',
    size: '63 capsules',
  },
  {
    id: 'p32',
    slug: 'forever-therm',
    name: 'Forever Therm',
    nameAr: 'فوريفر ثيرم',
    category: 'Fitness & Minceur',
    price: 41,
    rating: 4.6,
    reviewCount: 79,
    tagline: 'Thé vert, café vert et guarana pour contrôler le poids et l\'énergie.',
    taglineAr: 'شاي أخضر، قهوة خضراء وجوارانا للتحكم بالوزن والطاقة.',
    description:
      "Forever Therm est un brûleur de graisses qui contient des extraits de plantes (thé vert, café vert, guarana) associés à des vitamines du groupe B et de la vitamine C. Aide à contrôler le poids et réduire la fatigue.",
    ingredients: ['Thé vert', 'Guarana', 'Café vert', '8 vitamines (B1, B2, B3, B5, B6, B9, B12, C)'],
    howToUse: 'Prendre 2 comprimés le matin.',
    image: '/products/page-23.jpg',
    size: '60 comprimés',
  },
  {
    id: 'p33',
    slug: 'forever-lite-ultra-vanille',
    name: 'Forever Lite Ultra — Vanille',
    nameAr: 'لايت ألترا فوريفر - فانيليا',
    category: 'Fitness & Minceur',
    price: 48,
    rating: 4.8,
    reviewCount: 211,
    tagline: '24g de protéines et 21 vitamines & minéraux par dose, le shake idéal.',
    taglineAr: '24 غ من البروتين و21 فيتاميناً ومعدناً في كل جرعة.',
    description:
      "Forever Lite Ultra est idéal pour compléter un repas léger et apporter protéines, glucides, vitamines et minéraux. Les protéines participent au maintien de la masse musculaire. 180 calories par portion.",
    descriptionAr:
      'Forever Lite Ultra مثالي لاستكمال وجبة خفيفة وتوفير البروتينات والكربوهيدرات والفيتامينات والمعادن. تساهم البروتينات في الحفاظ على الكتلة العضلية. 180 سعرة حرارية لكل حصة.',
    ingredients: ['Vitamines B1, B2, B3, B5, B6, B8, B9, B12, D, E', 'Protéines', 'Contient soja et lait'],
    ingredientsAr: ['فيتامينات B1، B2، B3، B5، B6، B8، B9، B12، D، E', 'بروتينات', 'يحتوي على الصويا والحليب'],
    howToUse: "Dans un mixeur : 1 cuillère doseuse, 240 ml de boisson, fruits au choix et glaçons. Mixer 20 à 30 secondes.",
    howToUseAr: 'في الخلاط: ملعقة قياس واحدة، 240 مل من السائل، فواكه حسب الاختيار ومكعبات ثلج. اخلط لمدة 20 إلى 30 ثانية.',
    image: '/products/page-25.jpg',
    size: '470 g',
    bestSeller: true,
  },
  {
    id: 'p34',
    slug: 'forever-lite-ultra-chocolat',
    name: 'Forever Lite Ultra — Chocolat',
    nameAr: 'لايت ألترا فوريفر - شوكولاتة',
    category: 'Fitness & Minceur',
    price: 48,
    rating: 4.7,
    reviewCount: 174,
    tagline: '24g de protéines et 21 vitamines & minéraux par dose, le shake idéal.',
    taglineAr: '24 غ من البروتين و21 فيتاميناً ومعدناً في كل جرعة.',
    description:
      "Forever Lite Ultra est idéal pour compléter un repas léger et apporter protéines, glucides, vitamines et minéraux. Les protéines participent au maintien de la masse musculaire. 180 calories par portion.",
    ingredients: ['Vitamines B1, B2, B3, B5, B6, B8, B9, B12, D, E', 'Protéines', 'Contient soja et lait'],
    howToUse: "Dans un mixeur : 1 cuillère doseuse, 240 ml de boisson, fruits au choix et glaçons. Mixer 20 à 30 secondes.",
    image: '/products/page-25.jpg',
    size: '471 g',
  },

  // ---------- Packs ----------
  {
    id: 'p35',
    slug: 'pack-detox-pulpe',
    name: 'Pack Detox — Pulpe d\'Aloès',
    nameAr: 'حزمة ديتوكس - لب الألوة',
    category: 'Packs',
    price: 95,
    rating: 4.8,
    reviewCount: 63,
    tagline: 'Détoxifier le corps, sensation de légèreté et énergie retrouvée.',
    taglineAr: 'تخليص الجسم من السموم، شعور بالخفة وطاقة متجددة.',
    description:
      "Objectif : un corps ferme et tonique. Les résultats apparaissent dès les premiers jours : détoxification, sensation de légèreté et énergie retrouvée.",
    descriptionAr: 'الهدف: جسم مشدود ومتناسق. تظهر النتائج منذ الأيام الأولى: تخلص من السموم، شعور بالخفة وطاقة متجددة.',
    ingredients: [],
    howToUse: "Suivre le livret de programme inclus pendant la durée du programme Detox.",
    howToUseAr: 'اتبع كتيب البرنامج المرفق طوال مدة برنامج ديتوكس.',
    image: '/products/page-26.jpg',
    size: '1 programme',
    packContents: [
      '1x Forever Ultra Lite (Vanille ou Chocolat)',
      "2x Pulpes d'Aloès Stabilisée",
      '1x Forever Fields of Greens',
      '1x Forever Active Pro-B',
      '1x Livret de suivi du programme',
    ],
    bestSeller: true,
  },
  {
    id: 'p36',
    slug: 'pack-detox-berry',
    name: 'Pack Detox — Aloe Berry Nectar',
    nameAr: 'حزمة ديتوكس - ألوفيرا بيري نكتار',
    category: 'Packs',
    price: 95,
    rating: 4.7,
    reviewCount: 51,
    tagline: 'Détoxifier le corps, sensation de légèreté et énergie retrouvée.',
    taglineAr: 'تخليص الجسم من السموم، شعور بالخفة وطاقة متجددة.',
    description:
      "Objectif : un corps ferme et tonique. Les résultats apparaissent dès les premiers jours : détoxification, sensation de légèreté et énergie retrouvée.",
    ingredients: [],
    howToUse: "Suivre le livret de programme inclus pendant la durée du programme Detox.",
    image: '/products/page-26.jpg',
    size: '1 programme',
    packContents: [
      '1x Forever Ultra Lite (Vanille ou Chocolat)',
      '2x Aloe Berry Nectar',
      '1x Forever Fields of Greens',
      '1x Forever Active Pro-B',
      '1x Livret de suivi du programme',
    ],
  },
  {
    id: 'p37',
    slug: 'smart-consumer-pack',
    name: 'Smart Consumer Pack',
    nameAr: 'حزمة المستهلك الذكية',
    category: 'Packs',
    price: 49,
    rating: 4.6,
    reviewCount: 38,
    tagline: '4 produits essentiels à utiliser tous les jours.',
    taglineAr: '4 منتجات أساسية للاستخدام اليومي.',
    description:
      "Découvrez nos produits grâce à ce nouveau pack : 4 produits parmi nos essentiels pour avoir le meilleur de Forever à portée de main.",
    ingredients: [],
    howToUse: 'À utiliser dans le cadre de votre routine quotidienne.',
    image: '/products/page-27.jpg',
    size: '4 produits',
    packContents: [
      'Forever Aloe Lips with Jojoba',
      'Forever Bright Aloe Body Lotion',
      'Forever Aloe Pêche 330 ml',
      'Totebag siglé Forever Living Products',
    ],
  },
  {
    id: 'p38',
    slug: 'pack-hygiene',
    name: 'Pack Hygiène',
    nameAr: 'حزمة العناية اليومية',
    category: 'Packs',
    price: 89,
    rating: 4.7,
    reviewCount: 44,
    tagline: 'Produits d\'hygiène et cosmétiques pour toute la famille.',
    taglineAr: 'منتجات عناية ونظافة لكل العائلة.',
    description: "Le pack Hygiène réunit les indispensables Forever pour le soin du corps et du visage au quotidien.",
    ingredients: [],
    howToUse: 'À intégrer dans votre routine quotidienne.',
    image: '/products/page-28.jpg',
    size: '5 produits',
    packContents: [
      '1x Aloe First',
      '1x Aloe Liquid Soap',
      '2x Stick Déodorant Aloès',
      '1x Avocado Face & Body Soap',
      '1x Shampoing Aloe-Jojoba',
      '1x Après-shampoing Aloe-Jojoba',
    ],
  },
  {
    id: 'p39',
    slug: 'programme-bien-etre',
    name: 'Programme Bien-être',
    nameAr: 'برنامج العافية',
    category: 'Packs',
    price: 119,
    rating: 4.8,
    reviewCount: 57,
    tagline: 'Un bien-être au quotidien, de l\'intérieur comme de l\'extérieur.',
    taglineAr: 'عافية يومية، من الداخل والخارج.',
    description: "Le pack Bien-être associe nutrition et soin du corps pour un programme complet de bien-être quotidien.",
    ingredients: [],
    howToUse: 'À suivre quotidiennement, en complément d\'une alimentation équilibrée.',
    image: '/products/page-28.jpg',
    size: '6 produits',
    packContents: [
      "1x Pulpe d'Aloès Stabilisée",
      '1x Aloe Berry Nectar',
      '1x Forever Active Pro-B',
      '1x Forever Absorbent-C',
      '1x Forever Fields of Greens',
      '2x Forever Bright Aloès',
    ],
  },
  {
    id: 'p40',
    slug: 'pack-go2fbo',
    name: 'Pack de Démarrage — GO2FBO',
    nameAr: 'حزمة الانطلاق - GO2FBO',
    category: 'Packs',
    price: 175,
    rating: 4.8,
    reviewCount: 29,
    tagline: 'Le pack de démarrage complet pour découvrir l\'univers Forever.',
    taglineAr: 'حزمة الانطلاق الكاملة لاكتشاف عالم فوريفر.',
    description: "Le programme GO2FBO réunit une large sélection de produits phares pour découvrir l'ensemble des gammes Forever.",
    ingredients: [],
    howToUse: 'Idéal pour démarrer votre activité de distributeur ou découvrir la marque.',
    image: '/products/page-29.jpg',
    size: 'Pack complet',
    packContents: [
      '2x Mini Aloe Vera Gel',
      'Aloe-Jojoba Shampoo & Conditioner',
      'Aloe Heat Lotion',
      'Forever Arctic Sea',
      'Aloe Avocado Soap',
      'Aloe Sunscreen',
      'Forever Absorbent-C',
      'Forever Ail & Thym',
      'Forever Bee Pollen',
      'Forever Daily',
      'Forever Kids',
    ],
    new: true,
  },
  {
    id: 'p41',
    slug: 'start-your-journey-pack',
    name: 'Start Your Journey Pack',
    nameAr: 'حزمة بداية الرحلة',
    category: 'Packs',
    price: 149,
    rating: 4.7,
    reviewCount: 33,
    tagline: 'Quatre produits essentiels pour démarrer votre routine Forever.',
    taglineAr: 'أربعة منتجات أساسية لبدء روتينك مع فوريفر.',
    description: "Un pack pensé pour accompagner vos premiers pas avec les produits Forever au quotidien.",
    ingredients: [],
    howToUse: 'À utiliser quotidiennement pour intégrer les essentiels Forever à votre routine.',
    image: '/products/page-29.jpg',
    size: 'Pack complet',
    packContents: [
      '4x Forever Aloe Lips with Jojoba',
      '2x Forever Bright Toothgel',
      '1x Aloe Propolis Crème',
      '1x Aloe Vera Gelly',
      '2x Aloe Ever-Shield Deodorant',
      '1x Aloe Moisturizing Lotion',
      '1x Aloe Body Wash',
      '1x Aloe Body Lotion',
    ],
    new: true,
  },

  // ---------- Beauté ----------
  {
    id: 'p42',
    slug: 'aloe-first',
    name: 'Aloe First',
    nameAr: 'ألوي فيرست',
    category: 'Beauté',
    price: 27,
    rating: 4.8,
    reviewCount: 198,
    tagline: 'La brume quotidienne pour hydrater, rafraîchir et tonifier l\'épiderme.',
    taglineAr: 'الرذاذ اليومي للترطيب والانتعاش وتنشيط البشرة.',
    description:
      "Aloe First est la brume à utiliser quotidiennement pour hydrater, rafraîchir et tonifier l'épiderme du visage et du corps grâce à sa formule enrichie de 11 extraits de plantes, d'Aloe Vera, de propolis et d'allantoïne. Son pH neutre s'adapte aux peaux les plus sensibles.",
    descriptionAr:
      'Aloe First هو الرذاذ الذي يُستخدم يومياً لترطيب وإنعاش وتنشيط بشرة الوجه والجسم بفضل تركيبته الغنية بـ11 مستخلصاً نباتياً والألوفيرا والبروبوليس والألانتوين. درجة حموضته المتعادلة تناسب حتى أكثر البشرات حساسية.',
    ingredients: ["80,3% de gel d'aloès", '11 extraits de plantes', 'Propolis', 'Allantoïne'],
    ingredientsAr: ['80.3% جل ألوة', '11 مستخلصاً نباتياً', 'بروبوليس', 'ألانتوين'],
    howToUse: "Avant l'application de soins cosmétiques et à tout moment de la journée pour hydrater la peau.",
    howToUseAr: 'قبل تطبيق العناية التجميلية وفي أي وقت من اليوم لترطيب البشرة.',
    image: '/products/page-31.jpg',
    size: '118 ml',
    bestSeller: true,
  },
  {
    id: 'p43',
    slug: 'aloe-propolis-creme',
    name: 'Aloe Propolis Crème',
    nameAr: 'كريم البروبوليس بالألوة',
    category: 'Beauté',
    price: 24,
    rating: 4.8,
    reviewCount: 167,
    tagline: 'Un véritable soin anti-bactérien et réparateur pour les irritations cutanées.',
    taglineAr: 'عناية حقيقية مضادة للبكتيريا ومُصلحة لتهيجات البشرة.',
    description:
      "L'aloès associé à la propolis font de cette crème à la texture riche un véritable soin anti-bactérien et réparateur. La camomille, l'allantoïne et les vitamines A et E apportent à la peau douceur et souplesse.",
    descriptionAr:
      'الألوة المرتبطة بالبروبوليس تجعل من هذا الكريم ذي القوام الغني عناية حقيقية مضادة للبكتيريا ومُصلحة. البابونج والألانتوين وفيتامينات A وE تمنح البشرة نعومة ومرونة.',
    ingredients: ["74,1% de gel d'aloès", '0,5% propolis', 'Camomille', 'Allantoïne', 'Vitamines A et E'],
    ingredientsAr: ['74.1% جل ألوة', '0.5% بروبوليس', 'بابونج', 'ألانتوين', 'فيتامينات A وE'],
    howToUse: 'Appliquer sur une peau parfaitement nettoyée.',
    howToUseAr: 'يُطبق على بشرة نظيفة تماماً.',
    image: '/products/page-31.jpg',
    size: '113 g',
    bestSeller: true,
  },
  {
    id: 'p44',
    slug: 'gelee-aloes',
    name: 'Gelée Aloès',
    nameAr: 'جل الألوة',
    category: 'Beauté',
    price: 19,
    rating: 4.7,
    reviewCount: 112,
    tagline: 'Gel transparent non gras, idéal contre irritations et coups de soleil.',
    taglineAr: 'جل شفاف غير دهني، مثالي للتهيجات وحروق الشمس.',
    description:
      "Particulièrement riche en Aloe Vera, ce gel transparent non gras possède toutes les vertus de la plante. Il hydrate et régénère l'épiderme. Idéal contre les irritations de la peau et les coups de soleil.",
    ingredients: ["84,4% de gel d'aloès"],
    howToUse: 'Appliquer généreusement sur une peau parfaitement nettoyée.',
    image: '/products/page-31.jpg',
    size: '473 ml',
  },
  {
    id: 'p45',
    slug: 'aloe-body-lotion',
    name: 'Aloe Body Lotion',
    nameAr: 'لوشن الجسم بالألوة',
    category: 'Beauté',
    price: 23,
    rating: 4.8,
    reviewCount: 156,
    tagline: 'Apaise, hydrate et protège la peau du dessèchement.',
    taglineAr: 'يهدئ ويرطب ويحمي البشرة من الجفاف.',
    description:
      "L'Aloe Body Lotion apaise, hydrate et protège la peau du dessèchement. Grâce à sa concentration en gel d'Aloe Vera, huile d'argan, vitamine E et huile de macadamia, elle pénètre rapidement et laisse la peau souple. Sans silicone.",
    ingredients: ["Gel Aloe Vera", "Huile d'argan", 'Vitamine E', 'Huile de graines de macadamia'],
    howToUse: 'Appliquer généreusement et masser doucement jusqu\'à absorption complète.',
    image: '/products/page-32.jpg',
    size: '236 ml',
  },
  {
    id: 'p46',
    slug: 'aloe-liquid-soap',
    name: 'Aloe Liquid Soap',
    nameAr: 'صابون الألوة السائل',
    category: 'Beauté',
    price: 18,
    rating: 4.7,
    reviewCount: 121,
    tagline: 'Savon doux pour le visage, le corps et les cheveux, dès 3 ans.',
    taglineAr: 'صابون لطيف للوجه والجسم والشعر، من سن 3 سنوات.',
    description:
      "L'Aloe Liquid Soap est un savon pour le visage, le corps et les cheveux à destination de toute la famille. Sa formule très douce nettoie délicatement, respecte la peau et les cheveux, hydrate et préserve du dessèchement.",
    ingredients: ["39% de Gel d'Aloe vera", 'Agents lavants de noix de coco', 'Extrait de concombre et jojoba', "Huile d'Argan", "Glycérine végétale"],
    howToUse: 'Émulsionner sur peau ou cheveux mouillés, rincer abondamment.',
    image: '/products/page-33.jpg',
    size: '473 ml',
    new: true,
  },
  {
    id: 'p47',
    slug: 'forever-bright-toothgel',
    name: 'Forever Bright Toothgel',
    nameAr: 'معجون الأسنان برايت فوريفر',
    category: 'Beauté',
    price: 14,
    rating: 4.7,
    reviewCount: 143,
    tagline: 'Gel dentaire sans fluor qui ravive l\'émail des dents.',
    taglineAr: 'جل أسنان بدون فلورايد يُجدد مينا الأسنان.',
    description:
      "Ce gel dentaire, sans fluor et non abrasif, ravive l'émail de vos dents. Son complexe à la chlorophylle, sans menthol, procure une sensation de fraîcheur naturelle grâce à la propolis et à l'aloès.",
    descriptionAr:
      'جل الأسنان هذا، الخالي من الفلورايد وغير الكاشط، يُجدد مينا أسنانك. مركبه من الكلوروفيل، بدون منثول، يمنح إحساساً طبيعياً بالانتعاش بفضل البروبوليس والألوة.',
    ingredients: ["35,5% de gel d'aloès", 'Chlorophylle', 'Propolis'],
    ingredientsAr: ['35.5% جل ألوة', 'كلوروفيل', 'بروبوليس'],
    howToUse: 'Se brosser les dents après chaque repas.',
    howToUseAr: 'تنظيف الأسنان بالفرشاة بعد كل وجبة.',
    image: '/products/page-34.jpg',
    size: '130 g',
    bestSeller: true,
  },
  {
    id: 'p48',
    slug: 'stick-deodorant-aloes',
    name: 'Aloe Ever-Shield — Stick Déodorant',
    nameAr: 'مزيل العرق إيفر-شيلد بالألوة',
    category: 'Beauté',
    price: 13,
    rating: 4.7,
    reviewCount: 132,
    tagline: 'Sans alcool, sans sels d\'aluminium, protection efficace sans tacher.',
    taglineAr: 'بدون كحول أو أملاح الألومنيوم، حماية فعالة بدون بقع.',
    description:
      "Sans alcool, sans sels d'aluminium et discrètement parfumé, ce déodorant assure une protection efficace sans tacher vos vêtements. Sa formule à l'aloès adoucit et hydrate la peau.",
    descriptionAr:
      'بدون كحول أو أملاح الألومنيوم ومعطر بلطف، يوفر هذا المزيل حماية فعالة بدون ترك بقع على ملابسك. تركيبته بالألوة تلين وترطب البشرة.',
    ingredients: ["Gel d'aloès"],
    ingredientsAr: ['جل الألوة'],
    howToUse: "Appliquer le matin ou avant l'effort sur une peau propre et sèche.",
    howToUseAr: 'يُطبق في الصباح أو قبل المجهود على بشرة نظيفة وجافة.',
    image: '/products/page-34.jpg',
    size: '67 g',
    bestSeller: true,
  },
  {
    id: 'p49',
    slug: 'instant-hand-cleanser',
    name: 'Instant Hand Cleanser',
    nameAr: 'منظف اليدين الفوري',
    category: 'Beauté',
    price: 9,
    rating: 4.5,
    reviewCount: 88,
    tagline: 'Nettoie les mains en toute sécurité où que vous soyez.',
    taglineAr: 'ينظف اليدين بأمان أينما كنت.',
    description:
      "Une formule gel pour nettoyer vos mains en toute sécurité où que vous soyez. Enrichie en Aloe Vera, sa formule parfume délicatement les mains sans les dessécher.",
    ingredients: ['Alcool', 'Aloe Vera'],
    howToUse: 'Verser une noisette de gel et frotter les mains jusqu\'à ce qu\'elles soient sèches.',
    image: '/products/page-34.jpg',
    size: '28 g',
  },
  {
    id: 'p50',
    slug: 'aloe-lips',
    name: 'Aloe Lèvres (Aloe Lips)',
    nameAr: 'بلسم الشفاه بالألوة',
    category: 'Beauté',
    price: 8,
    rating: 4.9,
    reviewCount: 287,
    tagline: 'Baume ultra-hydratant à l\'Aloe Vera, huile de jojoba et cire d\'abeille.',
    taglineAr: 'بلسم مرطب جداً بالألوفيرا وزيت الجوجوبا وشمع العسل.',
    description:
      "Une formule ultra-hydratante et protectrice pour ce baume à lèvres qui associe Aloe Vera, huile de jojoba et cire d'abeille. Apporte un confort réparateur pour les lèvres les plus desséchées.",
    descriptionAr:
      'تركيبة مرطبة وواقية للغاية لهذا البلسم الذي يجمع بين الألوفيرا وزيت الجوجوبا وشمع العسل. يوفر راحة مُصلحة للشفاه الأكثر جفافاً.',
    ingredients: ["27,5% de gel d'aloès", "20,4% d'huile de jojoba", "Cire d'abeille"],
    ingredientsAr: ['27.5% جل ألوة', '20.4% زيت جوجوبا', 'شمع العسل'],
    howToUse: 'Appliquer sur les lèvres dès que le besoin se fait sentir.',
    howToUseAr: 'يُطبق على الشفاه عند الحاجة.',
    image: '/products/page-35.jpg',
    size: '4,5 g',
    bestSeller: true,
  },
  {
    id: 'p51',
    slug: 'savon-avocat',
    name: 'Forever Avocado Face & Body Soap',
    nameAr: 'صابون الأفوكادو للوجه والجسم',
    category: 'Beauté',
    price: 12,
    rating: 4.7,
    reviewCount: 119,
    tagline: 'Beurre d\'avocat, nettoie toutes les peaux même les plus sensibles.',
    taglineAr: 'زبدة الأفوكادو، تنظف حتى أكثر البشرات حساسية.',
    description:
      "Enrichi en beurre d'avocat, le Savon à l'Avocat nettoie toutes les peaux même les plus sensibles en les hydratant. Son léger parfum de fleurs de citronnier apporte un véritable plaisir.",
    descriptionAr:
      'مُخصب بزبدة الأفوكادو، صابون الأفوكادو ينظف جميع أنواع البشرة حتى الأكثر حساسية مع ترطيبها. عطره الخفيف من زهور الليمون يمنح متعة حقيقية.',
    ingredients: ["Beurre d'avocat"],
    ingredientsAr: ['زبدة الأفوكادو'],
    howToUse: 'Émulsionner chaque jour sur peau mouillée.',
    howToUseAr: 'يُستحلب يومياً على بشرة مبللة.',
    image: '/products/page-35.jpg',
    size: '284 g',
    bestSeller: true,
  },
  {
    id: 'p52',
    slug: 'ecran-solaire-aloes',
    name: 'Aloe Sunscreen SPF 30',
    nameAr: 'واقي الشمس بالألوة SPF 30',
    category: 'Beauté',
    price: 26,
    rating: 4.6,
    reviewCount: 95,
    tagline: 'Protection SPF 30 avancée contre les UVA et UVB, sans effet blanc.',
    taglineAr: 'حماية SPF 30 متقدمة من الأشعة UVA وUVB، بدون أثر أبيض.',
    description:
      "Aloe Sunscreen combine le pouvoir apaisant de l'aloès avec de l'oxyde de zinc naturel pour une protection SPF 30 avancée contre les rayons UVA et UVB. Adaptée à tous les types de peau.",
    descriptionAr:
      'يجمع Aloe Sunscreen بين القوة المهدئة للألوة وأكسيد الزنك الطبيعي لحماية SPF 30 متقدمة من أشعة UVA وUVB. مناسب لجميع أنواع البشرة.',
    ingredients: ['Aloe vera', 'Vitamine E', 'Oxyde de zinc'],
    ingredientsAr: ['ألوفيرا', 'فيتامين E', 'أكسيد الزنك'],
    howToUse: "Appliquer uniformément avant toute exposition au soleil. Renouveler toutes les 2 heures.",
    howToUseAr: 'يُطبق بانتظام وبسخاء قبل أي تعرض للشمس. يُجدد كل ساعتين.',
    image: '/products/page-36.jpg',
    size: '177 ml',
    bestSeller: true,
  },
  {
    id: 'p53',
    slug: 'gentlemans-pride',
    name: "Gentleman's Pride",
    nameAr: 'جنتلمانز برايد',
    category: 'Beauté',
    price: 21,
    rating: 4.6,
    reviewCount: 73,
    tagline: 'Crème fluide et apaisante pour calmer le feu du rasoir.',
    taglineAr: 'كريم سائل مهدئ لتهدئة تهيج الحلاقة.',
    description:
      "Gentleman's Pride est une crème fluide et légère, aux propriétés apaisantes pour calmer le feu du rasoir et les irritations. Son parfum subtil apporte une note d'élégance discrète.",
    ingredients: ["41,8% de gel d'aloès"],
    howToUse: 'Appliquer quotidiennement sur tout le visage après le rasage.',
    image: '/products/page-36.jpg',
    size: '118 ml',
  },
  {
    id: 'p54',
    slug: 'aloe-moisturizing-lotion',
    name: 'Aloe Moisturizing Lotion',
    nameAr: 'لوشن الترطيب بالألوة',
    category: 'Beauté',
    price: 22,
    rating: 4.6,
    reviewCount: 81,
    tagline: 'Protège, nourrit et réduit les signes du vieillissement cutané.',
    taglineAr: 'يحمي ويغذي ويقلل من علامات شيخوخة البشرة.',
    description:
      "Ce soin protège, nourrit et réduit les signes du vieillissement cutané. Sa texture fondante, enrichie en collagène et en élastine, hydrate et repulpe. Convient aux peaux sensibles.",
    ingredients: ["36,5% de gel d'aloès", 'Collagène', 'Élastine'],
    howToUse: "Appliquer matin et soir après l'Aloe First.",
    image: '/products/page-36.jpg',
    size: '120 ml',
  },
  {
    id: 'p55',
    slug: 'r3-factor',
    name: 'R3 Factor',
    nameAr: 'آر3 فاكتور',
    category: 'Beauté',
    price: 39,
    rating: 4.7,
    reviewCount: 76,
    tagline: 'Répare, renouvelle, repulpe — exfoliation naturelle de la peau.',
    taglineAr: 'يُصلح، يجدد، يملأ - تقشير طبيعي للبشرة.',
    description:
      "Répare, renouvelle, repulpe. Ce soin favorise l'exfoliation naturelle de la peau et diminue l'apparence des pores. Les rides et ridules sont lissées, le grain de peau est plus fin.",
    ingredients: ["35,48% de gel d'aloès"],
    howToUse: "Appliquer matin et soir sur peau nettoyée. Par temps ensoleillé, protéger la peau avec l'Écran Solaire Aloès.",
    image: '/products/page-37.jpg',
    size: '69 g',
  },
  {
    id: 'p56',
    slug: 'serum-alpha-e-factor',
    name: 'Sérum Alpha-E Factor',
    nameAr: 'سيروم ألفا-إي فاكتور',
    category: 'Beauté',
    price: 44,
    rating: 4.7,
    reviewCount: 68,
    tagline: 'Véritable bouclier anti-âge aux antioxydants puissants.',
    taglineAr: 'درع حقيقي مضاد للشيخوخة بمضادات أكسدة قوية.',
    description:
      "Véritable bouclier anti-âge, ce sérum allie des antioxydants puissants pour réduire les signes du vieillissement et les agressions cutanées. La peau retrouve son éclat.",
    ingredients: ['Vitamines A et E', 'Bisabolol', 'Huile de bourrache', "Gel d'aloès"],
    howToUse: 'Appliquer seul ou avant votre soin.',
    image: '/products/page-37.jpg',
    size: '187 ml',
  },
  {
    id: 'p57',
    slug: 'aloe-body-wash',
    name: 'Aloe Body Wash',
    nameAr: 'غسول الجسم بالألوة',
    category: 'Beauté',
    price: 20,
    rating: 4.7,
    reviewCount: 104,
    tagline: 'Nettoie et revitalise la peau délicatement tout en respectant son équilibre.',
    taglineAr: 'ينظف وينشط البشرة بلطف مع الحفاظ على توازنها.',
    description:
      "Grâce à sa formule très douce, l'Aloe Body Wash nettoie et revitalise la peau délicatement. Sa texture émulsion-gel fraîche laisse un parfum envoûtant et une peau propre, douce et bien hydratée.",
    ingredients: ['Gel Aloe Vera', 'Vitamines A, C, E'],
    howToUse: "Appliquer sur un luffa ou une éponge, savonner en mouvements circulaires, bien rincer.",
    image: '/products/page-38.jpg',
    size: '236 ml',
  },

  // ---------- Cheveux ----------
  {
    id: 'p58',
    slug: 'shampoing-aloe-jojoba',
    name: 'Shampoing Aloe-Jojoba',
    nameAr: 'شامبو الألوة والجوجوبا',
    category: 'Cheveux',
    price: 21,
    rating: 4.7,
    reviewCount: 138,
    tagline: 'Nettoie en profondeur et hydrate tous les types de cheveux.',
    taglineAr: 'ينظف بعمق ويرطب جميع أنواع الشعر.',
    description:
      "Conçu pour nettoyer en profondeur et hydrater tous les types de cheveux. En associant l'Aloe vera pur à l'huile de jojoba fortifiante et l'huile d'argan, ce shampoing est parfait pour un usage quotidien. Sans sulfates ajoutés.",
    ingredients: ["39,7% de gel d'aloès", 'Huile de jojoba', "Huile d'argan", "Huile d'églantier"],
    howToUse: 'Appliquer une noix de produit, masser, rincer abondamment.',
    image: '/products/page-39.jpg',
    size: '296 ml',
  },
  {
    id: 'p59',
    slug: 'apres-shampoing-aloe-jojoba',
    name: 'Après-Shampoing Aloe-Jojoba',
    nameAr: 'بلسم الألوة والجوجوبا',
    category: 'Cheveux',
    price: 21,
    rating: 4.7,
    reviewCount: 109,
    tagline: 'Adoucit, démêle, nourrit les cheveux et leur donne de la brillance.',
    taglineAr: 'يلين وينعم ويغذي الشعر ويمنحه لمعاناً.',
    description:
      "L'après-shampoing est un soin indispensable pour adoucir, démêler, nourrir les cheveux et leur donner de la brillance. Stimule également l'hydratation des cheveux et du cuir chevelu, sans sulfate.",
    ingredients: ["40,7% de gel d'aloès", 'Huile de jojoba', "Huile d'argan", "Huile d'églantier"],
    howToUse: "Appliquer sur l'ensemble de la chevelure en insistant sur les pointes, laisser agir puis rincer.",
    image: '/products/page-39.jpg',
    size: '296 ml',
  },

  // ---------- Sonya ----------
  {
    id: 'p60',
    slug: 'sonya-gel-nettoyant',
    name: 'Sonya — Gel Nettoyant',
    nameAr: 'سونيا - جل التنظيف',
    category: 'Sonya',
    price: 24,
    rating: 4.6,
    reviewCount: 62,
    tagline: 'Une toute nouvelle expérience du démaquillage, riche en Aloe vera et huile de Baobab.',
    taglineAr: 'تجربة جديدة كلياً لإزالة المكياج، غنية بالألوفيرا وزيت الباوباب.',
    description:
      "Le gel Nettoyant Sonya offre une toute nouvelle expérience du démaquillage. Il fond sur la peau et forme une mousse onctueuse, laissant la peau douce et hydratée.",
    ingredients: ["39,2% de gel d'aloès", 'Huile de Baobab'],
    howToUse: 'Utiliser matin et soir pour nettoyer le visage et le cou.',
    image: '/products/page-41.jpg',
    size: '177 ml',
  },
  {
    id: 'p61',
    slug: 'sonya-gel-eclat',
    name: 'Sonya — Gel Éclat',
    nameAr: 'سونيا - جل الإشراقة',
    category: 'Sonya',
    price: 26,
    rating: 4.6,
    reviewCount: 54,
    tagline: 'Retrouvez l\'éclat naturel de votre teint.',
    taglineAr: 'استعيدي إشراقة بشرتك الطبيعية.',
    description:
      "Retrouvez l'éclat naturel de votre teint grâce au gel Éclat Sonya. L'Aloe vera et des actifs végétaux hydratent la peau tandis qu'un peptide gomme les imperfections et uniformise le teint.",
    ingredients: ["42,9% de gel d'aloès"],
    howToUse: 'Appliquer sur le visage et le cou matin et soir.',
    image: '/products/page-41.jpg',
    size: '28,3 g',
  },
  {
    id: 'p62',
    slug: 'sonya-masque-gel',
    name: 'Sonya — Masque Gel',
    nameAr: 'سونيا - قناع جل',
    category: 'Sonya',
    price: 28,
    rating: 4.7,
    reviewCount: 58,
    tagline: 'À appliquer avant le coucher pour optimiser la récupération nocturne.',
    taglineAr: 'يُطبق قبل النوم لتحسين التجدد الليلي.',
    description:
      "À appliquer juste avant le coucher, le masque gel Sonya se transforme en une texture délicieusement fraîche et vite absorbée, optimisant le processus de récupération nocturne de la peau.",
    ingredients: ["43,2% de gel d'aloès"],
    howToUse: 'Appliquer au coucher et rincer au réveil, 2 à 3 fois par semaine.',
    image: '/products/page-41.jpg',
    size: '59 ml',
  },
  {
    id: 'p63',
    slug: 'sonya-gel-hydratant',
    name: 'Sonya — Gel Hydratant',
    nameAr: 'سونيا - جل الترطيب',
    category: 'Sonya',
    price: 27,
    rating: 4.7,
    reviewCount: 49,
    tagline: 'Fond sur la peau et unifie le teint, riche en Aloe vera.',
    taglineAr: 'يذوب على البشرة ويوحد لون البشرة، غني بالألوفيرا.',
    description:
      "Le Gel Hydratant Sonya fond sur la peau, l'enveloppe d'un voile de douceur et unifie le teint. Il associe l'Aloe vera à de nombreux extraits végétaux pour optimiser l'hydratation.",
    ingredients: ["37,9% de gel d'aloès"],
    howToUse: 'Appliquer sur le visage et le cou matin et soir.',
    image: '/products/page-41.jpg',
    size: '60 ml',
  },

  // ---------- Infinite ----------
  {
    id: 'p64',
    slug: 'infinite-demaquillant-hydratant',
    name: 'Infinite — Démaquillant Hydratant',
    nameAr: 'إنفينيت - مزيل مكياج مرطب',
    category: 'Infinite',
    price: 32,
    rating: 4.6,
    reviewCount: 41,
    tagline: 'Nettoie et hydrate la peau en un seul geste.',
    taglineAr: 'ينظف ويرطب البشرة بخطوة واحدة.',
    description:
      "Le Démaquillant Hydratant nettoie et hydrate la peau en un seul geste. L'actif nettoyant utilisé, extrait naturel de noix de coco, est hypoallergénique et non irritant.",
    ingredients: ["35% de gel d'aloès", 'Extrait naturel de noix de coco'],
    howToUse: 'Utiliser le matin et le soir pour nettoyer le visage et le cou.',
    image: '/products/page-42.jpg',
    size: '177 ml',
  },
  {
    id: 'p65',
    slug: 'infinite-serum-raffermissant',
    name: 'Infinite — Sérum Raffermissant',
    nameAr: 'إنفينيت - سيروم الشد',
    category: 'Infinite',
    price: 58,
    rating: 4.8,
    reviewCount: 67,
    tagline: 'Un véritable élixir de jeunesse à la chaîne de 3 acides aminés.',
    taglineAr: 'إكسير شباب حقيقي بسلسلة من 3 أحماض أمينية.',
    description:
      "Le Sérum Raffermissant est un véritable élixir de jeunesse. Il combat les signes visibles de l'âge en intensifiant la puissance de l'Aloe vera grâce à une chaîne spécifique de trois acides aminés.",
    descriptionAr:
      'السيروم المشدد هو إكسير شباب حقيقي. يحارب علامات التقدم في السن الظاهرة من خلال تكثيف قوة الألوفيرا بفضل سلسلة محددة من ثلاثة أحماض أمينية.',
    ingredients: ["49% gel d'aloès"],
    ingredientsAr: ['49% جل ألوة'],
    howToUse: 'Appliquer sur le visage et le cou préalablement nettoyés avec le Démaquillant Hydratant.',
    howToUseAr: 'يُطبق على الوجه والرقبة بعد التنظيف بمزيل المكياج المرطب.',
    image: '/products/page-42.jpg',
    size: '48,2 ml',
    bestSeller: true,
  },
  {
    id: 'p66',
    slug: 'infinite-creme-reparatrice',
    name: 'Infinite — Crème Réparatrice',
    nameAr: 'إنفينيت - كريم مُصلح',
    category: 'Infinite',
    price: 54,
    rating: 4.7,
    reviewCount: 59,
    tagline: 'Texture légère et onctueuse, double action hydratante et réparatrice.',
    taglineAr: 'قوام خفيف وناعم، مزدوج الفعالية للترطيب والإصلاح.',
    description:
      "La Crème Réparatrice, d'une texture légère et onctueuse, est riche en Aloe vera, extraits de plantes, huile de jojoba et vitamine B3. Le visage est visiblement repulpé, retrouvant jeunesse et élasticité.",
    ingredients: ["38% gel d'aloès", 'Huile de jojoba', 'Vitamine B3'],
    howToUse: 'Utiliser le soir au coucher après application du Sérum Raffermissant.',
    image: '/products/page-42.jpg',
    size: '555 ml',
  },
  {
    id: 'p67',
    slug: 'infinite-complexe-raffermissant',
    name: 'Infinite — Complexe Raffermissant',
    nameAr: 'إنفينيت - مركب الشد',
    category: 'Infinite',
    price: 49,
    rating: 4.6,
    reviewCount: 38,
    tagline: 'Lutte de l\'intérieur contre les signes apparents de l\'âge.',
    taglineAr: 'يحارب من الداخل علامات التقدم في السن الظاهرة.',
    description:
      "Le Complexe Raffermissant lutte de l'intérieur contre les signes apparents de l'âge. Il contient un extrait breveté de melon français, des phytocéramides ainsi que du collagène.",
    ingredients: ['Collagène (poisson)', 'Vitamine C', 'Céramides (blé)', 'Extrait de melon'],
    howToUse: 'Prendre 2 comprimés par jour avec un grand verre d\'eau.',
    image: '/products/page-42.jpg',
    size: '60 comprimés',
  },
  {
    id: 'p68',
    slug: 'infinite-lotion-tonifiante',
    name: 'Infinite — Lotion Tonifiante',
    nameAr: 'إنفينيت - لوشن منعش',
    category: 'Infinite',
    price: 34,
    rating: 4.6,
    reviewCount: 33,
    tagline: 'Apporte un véritable coup d\'éclat à la peau.',
    taglineAr: 'يمنح البشرة إشراقة حقيقية.',
    description:
      "Cette lotion tonifiante apporte un véritable coup d'éclat à la peau. Elle parfait le démaquillage et débarrasse la peau des dernières impuretés. Riche en Aloe Vera, extrait de concombre et de thé blanc.",
    ingredients: ["46,3% de gel d'aloès", 'Extrait de concombre', 'Thé blanc'],
    howToUse: 'Appliquer généreusement à l\'aide d\'un disque de coton sur le visage et le cou.',
    image: '/products/page-44.jpg',
    size: '177 ml',
  },
  {
    id: 'p69',
    slug: 'infinite-creme-contour-yeux',
    name: 'Infinite — Crème Contour des Yeux',
    nameAr: 'إنفينيت - كريم محيط العين',
    category: 'Infinite',
    price: 46,
    rating: 4.7,
    reviewCount: 51,
    tagline: 'Le secret d\'un regard sublimé, à l\'extrait de collagène.',
    taglineAr: 'سر نظرة متألقة، بمستخلص الكولاجين.',
    description:
      "La crème contour des yeux est le secret d'un regard sublimé. Elle allie l'Aloe vera à un extrait de collagène pour un regard visiblement rajeuni et à l'extrait d'arbre à soie pour effacer les signes de fatigue.",
    ingredients: ["35,2% de gel d'aloès", 'Extrait de collagène', "Extrait d'arbre à soie"],
    howToUse: 'Appliquer par petites touches autour des yeux en tapotant délicatement.',
    image: '/products/page-44.jpg',
    size: '21 g',
  },
  {
    id: 'p70',
    slug: 'infinite-soin-exfoliant',
    name: 'Infinite — Soin Exfoliant',
    nameAr: 'إنفينيت - مقشر للبشرة',
    category: 'Infinite',
    price: 36,
    rating: 4.6,
    reviewCount: 29,
    tagline: 'Faire peau neuve grâce au bromélaïne, papaïne et perles de jojoba.',
    taglineAr: 'بشرة جديدة بفضل البروميلين والبابايين ولؤلؤ الجوجوبا.',
    description:
      "Le Soin Exfoliant est l'allié idéal pour faire peau neuve et affinée. Votre peau est exfoliée et nettoyée en profondeur grâce au bromélaïne, papaïne, perles de jojoba et de bambou.",
    ingredients: ["34% de gel d'aloès", 'Bromélaïne', 'Papaïne', 'Perles de jojoba et de bambou'],
    howToUse: 'Appliquer sur le visage humide en mouvements circulaires, rincer abondamment.',
    image: '/products/page-45.jpg',
    size: '60 ml',
  },
  {
    id: 'p71',
    slug: 'infinite-activateur-aloes',
    name: 'Infinite — Activateur Aloès',
    nameAr: 'إنفينيت - منشط الألوة',
    category: 'Infinite',
    price: 30,
    rating: 4.6,
    reviewCount: 26,
    tagline: 'Soin indispensable pour parfaire le démaquillage et vitaliser le teint.',
    taglineAr: 'عناية أساسية لإتمام إزالة المكياج وتنشيط البشرة.',
    description:
      "Découvrez l'Activateur Aloès, soin indispensable qui peut être utilisé seul pour parfaire le démaquillage, hydrater la peau et vitaliser le teint.",
    ingredients: ["98,7% de gel d'Aloès"],
    howToUse: "Appliquer sur le visage et le cou à l'aide d'un coton.",
    image: '/products/page-45.jpg',
    size: '130 ml',
  },
  {
    id: 'p72',
    slug: 'infinite-serum-hydratant',
    name: 'Infinite — Sérum Hydratant',
    nameAr: 'إنفينيت - سيروم الترطيب',
    category: 'Infinite',
    price: 52,
    rating: 4.8,
    reviewCount: 47,
    tagline: '4 acides hyaluroniques pour cibler chaque couche de la peau.',
    taglineAr: '4 أحماض هيالورونيك لاستهداف كل طبقات البشرة.',
    description:
      "Le Sérum Hydratant repulpe et hydrate parfaitement votre épiderme tout en réduisant l'apparence des ridules et des rides grâce à l'association de 4 acides hyaluroniques.",
    ingredients: ["Gel d'aloès", '4 acides hyaluroniques'],
    howToUse: 'Appliquer 1 à 2 pressions sur tout le visage et le cou.',
    image: '/products/page-46.jpg',
    size: '18 ml',
  },
]

export const categories: Category[] = [
  'Packs',
  'Beauté',
  'Cheveux',
  'Nutrition',
  'Fitness & Minceur',
  'Sonya',
  'Infinite',
  "Pulpe d'Aloe Vera",
  'Produits de la Ruche',
]

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug)
}

export function getBestSellers() {
  return products.filter((p) => p.bestSeller)
}

export function getRelatedProducts(product: Product, count = 4) {
  return products.filter((p) => p.category === product.category && p.id !== product.id).slice(0, count)
}

export function getLocalizedProduct(product: Product, locale: 'fr' | 'ar'): Product {
  if (locale !== 'ar') return product
  return {
    ...product,
    name: product.nameAr ?? product.name,
    tagline: product.taglineAr ?? product.tagline,
    description: product.descriptionAr ?? product.description,
    ingredients: product.ingredientsAr ?? product.ingredients,
    howToUse: product.howToUseAr ?? product.howToUse,
  }
}
