-- Run in Supabase → SQL Editor → New query → Run.
-- Descriptions arabes pour LES 72 produits. Après exécution, chaque fiche
-- produit s'affiche en arabe quand le client passe le site en arabe.
-- (Idempotent : peut être relancé sans risque.)

update products set description_ar = 'تجدد ألوفيرا فوريفر مظهره! بفضل خبرة 40 عاماً، أعادت فوريفر تصميم منتجها المميز وابتكرت نسخة جديدة كلياً بدون مواد حافظة وغنية بفيتامين سي، في عبوة قابلة لإعادة التدوير بنسبة 100%. السر: 99.7% جل ألوفيرا وجرعة تآزرية من فيتامين سي.' where slug = 'aloe-vera-gel-330ml';
update products set description_ar = 'تجمع التركيبة الجديدة لألوفيرا بالخوخ بين الألوفيرا (84.5%) وهريس الخوخ وعصير العنب الأبيض المركّز لنكهة ناعمة، إضافة إلى جرعة تآزرية من فيتامين سي. عبوة قابلة لإعادة التدوير 100%.' where slug = 'aloe-peche-330ml';
update products set description_ar = 'جرعة كبيرة (90.7%) من لب الألوفيرا، مع لمسة من عصير التفاح والتوت البري، وفيتامين سي، بدون أي مواد حافظة، وعبوة قابلة لإعادة التدوير 100%.' where slug = 'aloe-berry-nectar-330ml';
update products set description_ar = 'بفضل 86% من جل الألوفيرا وهريس المانجو الطبيعي، يمنح هذا الإصدار الجديد دفعة إضافية من التغذية والنكهة. بدون مواد حافظة، ومصدر لفيتامين سي.' where slug = 'aloe-mangue-1l';
update products set description_ar = 'بطعمه المنعش اللذيذ، يحتوي ألوفيرا بيري نكتار على مستخلص التوت البري مع لب الألوفيرا. تساهم النبتة في دعم الدفاعات الطبيعية للجسم.' where slug = 'aloe-berry-nectar-1l';
update products set description_ar = 'لب الألوة المثبت هو المنتج الذي يُستخدم يومياً للحفاظ على عافية مثالية. تساهم الألوفيرا في دعم الجهاز المناعي وتحتوي على مضادات أكسدة قوية.' where slug = 'pulpe-aloe-vera-stabilisee-1l';
update products set description_ar = 'لذيذ وناعم، قلب الألوة مُخصّب بمركّز عصير الخوخ. تساعد الألوفيرا على تحفيز الأيض وتساهم في الدفاعات الطبيعية للجسم.' where slug = 'aloe-bits-n-peaches-1l';
update products set description_ar = 'العسل، المعروف بـ«ذهب الخلية»، ينتجه النحل من رحيق الأزهار. بفضل قوامه السائل، يسهل إضافة عسل فوريفر إلى الطعام، وعبوته عملية لتحديد الجرعة.' where slug = 'forever-bee-honey';
update products set description_ar = 'العكبر (البروبوليس) راتينج يجمعه نحل العسل من الأشجار ويحوّله. تُستخدم هذه المادة ذات الخصائص المضادة للميكروبات لحماية الخلية من الفطريات والبكتيريا.' where slug = 'forever-propolis';
update products set description_ar = 'يجمعه النحل من الأزهار، ويحسّن حبوب لقاح فوريفر حيوية الجسم ومقاومته عند تغيّر الفصول.' where slug = 'forever-bee-pollen';
update products set description_ar = 'الغذاء الملكي مثالي للوقاية من تداعيات فصل الشتاء. يعزّز الغذاء الملكي من فوريفر بلطف الدفاعات الطبيعية للجسم.' where slug = 'forever-royal-jelly';
update products set description_ar = 'تتكون فلورا الأمعاء من مليارات البكتيريا التي تساهم في حسن سير عمل الجسم. يجمع Forever Active Pro-B بشكل تآزري بين البروبيوتيك والبريبايوتيك.' where slug = 'forever-active-pro-b';
update products set description_ar = 'يحتوي فوريفر كيدز على 12 فيتاميناً (A، B، C، D، E) ومعدنين (الحديد والزنك). يساهم هذا المزيج في الأداء الطبيعي للجهاز المناعي، ويقلل التعب، ويدعم النمو الذهني.' where slug = 'forever-kids';
update products set description_ar = 'يُستخلص فيلدز أوف جرينز من براعم نباتية فتية: أوراق الشعير والقمح والفصفصة وفلفل الكايين.' where slug = 'fields-of-greens';
update products set description_ar = 'يساهم فيتامين سي في تقليل التعب واستعادة النشاط والطاقة. وهو ضروري لتقوية مقاومة الجسم.' where slug = 'forever-absorbent-c';
update products set description_ar = 'هيّئ عينيك لنمط حياة متصل بالشاشات! فوريفر آي فيجن مكمّل غذائي للرؤية بتركيبة كاملة من فيتامينات A وC وE والزنك.' where slug = 'forever-ivision';
update products set description_ar = 'يحتوي فوريفر سوبر جرينز على أكثر من 20 نوعاً من الفواكه والخضار، والألوفيرا، وفيتامين سي، والمغنيسيوم. يدعم هذا المزيج الدفاعات الطبيعية والتعافي العضلي.' where slug = 'forever-supergreens';
update products set description_ar = 'فوريفر إيميوبلند، مزيج من الفيتامينات والمعادن والفطريات المستخدمة تقليدياً في آسيا، يساهم في تحفيز الدفاعات المناعية للحفاظ على رصيدك الصحي.' where slug = 'forever-immublend';
update products set description_ar = 'تركيبة حصرية من 55 مكوناً تجمع بين عناصر مركّب AOS (أوليغوسكاريدات الألوة) والفيتامينات والمعادن والمغذيات النباتية من مستخلصات الفواكه والخضار.' where slug = 'forever-daily';
update products set description_ar = 'الثوم والزعتر من فوريفر مزيج فريد من مستخلصين نباتيين معروفين بتحسين الراحة الهضمية. كبسولة بدون رائحة تعادل 1000 ملغ من الثوم الطازج.' where slug = 'forever-ail-thym';
update products set description_ar = 'يوفر فوريفر فايبر 5 غرامات من الألياف الذائبة في الماء لتحفيز وظائف الأمعاء واستعادة راحة هضمية جيدة.' where slug = 'forever-fiber';
update products set description_ar = 'يجمع هذا المنقوع بنكهته اللطيفة الرقيقة بين الطعم المنعش لقشر البرتقال والليمون، والنكهات المتبّلة للقرفة والقرنفل. يمنح راحة هضمية.' where slug = 'infusion-fleur-aloes';
update products set description_ar = 'صُمّم هذا المزيج الطبيعي من النباتات والفيتامينات والمعادن خصيصاً للنساء. يساعد فيتامين B6 على تنظيم التوازن الهرموني، وتساعد زهرة الآلام على تقليل التوتر.' where slug = 'vitolize-femmes';
update products set description_ar = 'يحتوي فيتولايز للرجال على فيتامينات ومعادن وفيتوستيرول للحفاظ على أداء جيد للبروستاتا. ويساهم الزنك في الحفاظ على الخصوبة الطبيعية.' where slug = 'vitolize-hommes';
update products set description_ar = 'فوريفر موف مزيج من مكوّنين مسجّلين ببراءة اختراع: غشاء قشر البيض NEM® وكركم BioCurc®. يعملان بتآزر لدعم راحة مفصلية مثالية.' where slug = 'forever-move';
update products set description_ar = 'يحتوي فوريفر كالسيوم على فيتاميني C وD ومعادن (كالسيوم، مغنيسيوم، منغنيز، زنك، نحاس) للمساهمة في الحفاظ على عظام ووظيفة عضلية طبيعية.' where slug = 'forever-calcium';
update products set description_ar = 'يحتوي Forever Arctic-Sea على أحماض دهنية غير مشبعة، أوميغا-3، بما في ذلك EPA وDHA الموجودة في زيوت الأسماك والحبار. تساهم في الوظيفة الطبيعية للدماغ والقلب.' where slug = 'forever-arctic-sea';
update products set description_ar = 'الميثيل سلفونيل ميثان (MSM) مصدر مستقر وطبيعي للكبريت العضوي، موجود بتركيز عالٍ في المفاصل، ويساهم في الحفاظ على سلامة النسيج الضام.' where slug = 'aloe-msm-gel';
update products set description_ar = 'كريم التدليك هذا مكمّل مثالي لتخفيف آلام المفاصل أو تهيئة العضلات للمجهود بفضل المنثول وزيوت الأوكالبتوس والسمسم والجوجوبا والمشمش.' where slug = 'emulsion-thermogene';
update products set description_ar = 'حيوية وقوة وتحمّل ورياضة قصوى: يجمع فوريفر أرجي+ بين أل-أرجينين ومزيج فريد من الفيتامينات ومستخلصات الفواكه لمرافقة مثالية أثناء المجهود.' where slug = 'forever-argi-plus';
update products set description_ar = 'تتميز الألياف المستخلصة من صبار الأوبونتيا بقدرتها على جذب الدهون والسكريات واحتجازها. وتساعد بذور الفاصولياء البيضاء والكروم على تقليل السعرات الحرارية اليومية.' where slug = 'forever-lean';
update products set description_ar = 'فوريفر ثيرم حارق للدهون يحتوي على مستخلصات نباتية (الشاي الأخضر، القهوة الخضراء، الجوارانا) مع فيتامينات المجموعة B وفيتامين سي. يساعد على التحكم بالوزن وتقليل التعب.' where slug = 'forever-therm';
update products set description_ar = 'Forever Lite Ultra مثالي لاستكمال وجبة خفيفة وتوفير البروتينات والكربوهيدرات والفيتامينات والمعادن. تساهم البروتينات في الحفاظ على الكتلة العضلية. 180 سعرة حرارية لكل حصة.' where slug = 'forever-lite-ultra-vanille';
update products set description_ar = 'Forever Lite Ultra مثالي لاستكمال وجبة خفيفة وتوفير البروتينات والكربوهيدرات والفيتامينات والمعادن. تساهم البروتينات في الحفاظ على الكتلة العضلية. 180 سعرة حرارية لكل حصة.' where slug = 'forever-lite-ultra-chocolat';
update products set description_ar = 'الهدف: جسم مشدود ومتناسق. تظهر النتائج منذ الأيام الأولى: تخلّص من السموم، شعور بالخفة، وطاقة متجددة.' where slug = 'pack-detox-pulpe';
update products set description_ar = 'الهدف: جسم مشدود ومتناسق. تظهر النتائج منذ الأيام الأولى: تخلّص من السموم، شعور بالخفة، وطاقة متجددة.' where slug = 'pack-detox-berry';
update products set description_ar = 'اكتشف منتجاتنا عبر هذه الحزمة الجديدة: 4 منتجات من أساسياتنا لتحصل على أفضل ما في فوريفر بين يديك.' where slug = 'smart-consumer-pack';
update products set description_ar = 'تجمع حزمة العناية اليومية أساسيات فوريفر للعناية بالجسم والوجه يومياً.' where slug = 'pack-hygiene';
update products set description_ar = 'يجمع برنامج العافية بين التغذية والعناية بالجسم لبرنامج عافية يومي متكامل.' where slug = 'programme-bien-etre';
update products set description_ar = 'يجمع برنامج GO2FBO تشكيلة واسعة من المنتجات المميزة لاكتشاف جميع مجموعات فوريفر.' where slug = 'pack-go2fbo';
update products set description_ar = 'حزمة مصممة لمرافقة خطواتك الأولى مع منتجات فوريفر يومياً.' where slug = 'start-your-journey-pack';
update products set description_ar = 'Aloe First هو الرذاذ الذي يُستخدم يومياً لترطيب وإنعاش وتنشيط بشرة الوجه والجسم بفضل تركيبته الغنية بـ11 مستخلصاً نباتياً والألوفيرا والبروبوليس والألانتوين. درجة حموضته المتعادلة تناسب حتى أكثر البشرات حساسية.' where slug = 'aloe-first';
update products set description_ar = 'الألوة المرتبطة بالبروبوليس تجعل من هذا الكريم ذي القوام الغني عناية حقيقية مضادة للبكتيريا ومُصلحة. البابونج والألانتوين وفيتامينات A وE تمنح البشرة نعومة ومرونة.' where slug = 'aloe-propolis-creme';
update products set description_ar = 'غني جداً بالألوفيرا، يمتلك هذا الجل الشفاف غير الدهني كل فضائل النبتة. يرطب البشرة ويجددها. مثالي ضد تهيجات الجلد وحروق الشمس.' where slug = 'gelee-aloes';
update products set description_ar = 'يهدئ لوشن الجسم بالألوة ويرطب ويحمي البشرة من الجفاف. بفضل تركيزه من جل الألوفيرا وزيت الأركان وفيتامين E وزيت المكاداميا، يتغلغل بسرعة ويترك البشرة ناعمة. بدون سيليكون.' where slug = 'aloe-body-lotion';
update products set description_ar = 'صابون الألوة السائل صابون للوجه والجسم والشعر لكل أفراد العائلة. تركيبته اللطيفة جداً تنظف برفق، وتحترم البشرة والشعر، وترطب وتقي من الجفاف.' where slug = 'aloe-liquid-soap';
update products set description_ar = 'جل الأسنان هذا، الخالي من الفلورايد وغير الكاشط، يُجدد مينا أسنانك. مركبه من الكلوروفيل، بدون منثول، يمنح إحساساً طبيعياً بالانتعاش بفضل البروبوليس والألوة.' where slug = 'forever-bright-toothgel';
update products set description_ar = 'بدون كحول أو أملاح الألومنيوم ومعطر بلطف، يوفر هذا المزيل حماية فعالة بدون ترك بقع على ملابسك. تركيبته بالألوة تلين وترطب البشرة.' where slug = 'stick-deodorant-aloes';
update products set description_ar = 'تركيبة جل لتنظيف يديك بأمان أينما كنت. مُخصبة بالألوفيرا، تعطر تركيبته اليدين بلطف دون أن تجففهما.' where slug = 'instant-hand-cleanser';
update products set description_ar = 'تركيبة مرطبة وواقية للغاية لهذا البلسم الذي يجمع بين الألوفيرا وزيت الجوجوبا وشمع العسل. يوفر راحة مُصلحة للشفاه الأكثر جفافاً.' where slug = 'aloe-lips';
update products set description_ar = 'مُخصب بزبدة الأفوكادو، صابون الأفوكادو ينظف جميع أنواع البشرة حتى الأكثر حساسية مع ترطيبها. عطره الخفيف من زهور الليمون يمنح متعة حقيقية.' where slug = 'savon-avocat';
update products set description_ar = 'يجمع Aloe Sunscreen بين القوة المهدئة للألوة وأكسيد الزنك الطبيعي لحماية SPF 30 متقدمة من أشعة UVA وUVB. مناسب لجميع أنواع البشرة.' where slug = 'ecran-solaire-aloes';
update products set description_ar = 'جنتلمانز برايد كريم سائل خفيف بخصائص مهدئة لتهدئة تهيج الحلاقة والاحمرار. عطره اللطيف يمنح لمسة أناقة هادئة.' where slug = 'gentlemans-pride';
update products set description_ar = 'تحمي هذه العناية وتغذي وتقلل من علامات شيخوخة البشرة. قوامها الذائب، المُخصب بالكولاجين والإيلاستين، يرطب ويملأ البشرة. مناسبة للبشرة الحساسة.' where slug = 'aloe-moisturizing-lotion';
update products set description_ar = 'يُصلح، يجدد، يملأ. تدعم هذه العناية التقشير الطبيعي للبشرة وتقلل من ظهور المسام. تُنعَّم التجاعيد والخطوط الدقيقة، ويصبح ملمس البشرة أدق.' where slug = 'r3-factor';
update products set description_ar = 'درع حقيقي مضاد للشيخوخة، يجمع هذا السيروم بين مضادات أكسدة قوية لتقليل علامات التقدم في السن والعوامل المؤثرة على البشرة. تستعيد البشرة إشراقتها.' where slug = 'serum-alpha-e-factor';
update products set description_ar = 'بفضل تركيبته اللطيفة جداً، ينظف غسول الجسم بالألوة البشرة وينشطها برفق. قوامه المنعش يترك عطراً أخّاذاً وبشرة نظيفة وناعمة ومرطبة جيداً.' where slug = 'aloe-body-wash';
update products set description_ar = 'مصمم لتنظيف جميع أنواع الشعر بعمق وترطيبها. بجمعه بين الألوفيرا النقية وزيت الجوجوبا المقوّي وزيت الأركان، هذا الشامبو مثالي للاستخدام اليومي. بدون كبريتات مضافة.' where slug = 'shampoing-aloe-jojoba';
update products set description_ar = 'البلسم عناية أساسية لتنعيم الشعر وفك تشابكه وتغذيته ومنحه لمعاناً. يحفّز أيضاً ترطيب الشعر وفروة الرأس، بدون كبريتات.' where slug = 'apres-shampoing-aloe-jojoba';
update products set description_ar = 'يقدم جل التنظيف من سونيا تجربة جديدة كلياً لإزالة المكياج. يذوب على البشرة ويشكّل رغوة ناعمة، تاركاً البشرة ناعمة ومرطبة.' where slug = 'sonya-gel-nettoyant';
update products set description_ar = 'استعيدي إشراقة بشرتك الطبيعية بفضل جل الإشراقة من سونيا. ترطب الألوفيرا والمكونات النباتية البشرة، بينما يخفي أحد الببتيدات الشوائب ويوحّد لون البشرة.' where slug = 'sonya-gel-eclat';
update products set description_ar = 'يُطبق قبل النوم مباشرة، يتحول قناع الجل من سونيا إلى قوام منعش لذيذ سريع الامتصاص، ما يحسّن عملية تجدد البشرة الليلي.' where slug = 'sonya-masque-gel';
update products set description_ar = 'يذوب جل الترطيب من سونيا على البشرة، ويغلفها بستار من النعومة ويوحّد لونها. يجمع بين الألوفيرا والعديد من المستخلصات النباتية لترطيب أمثل.' where slug = 'sonya-gel-hydratant';
update products set description_ar = 'ينظف مزيل المكياج المرطب البشرة ويرطبها بخطوة واحدة. المكوّن المنظّف المستخدم، مستخلص طبيعي من جوز الهند، مضاد للحساسية وغير مهيّج.' where slug = 'infinite-demaquillant-hydratant';
update products set description_ar = 'السيروم المشدد هو إكسير شباب حقيقي. يحارب علامات التقدم في السن الظاهرة من خلال تكثيف قوة الألوفيرا بفضل سلسلة محددة من ثلاثة أحماض أمينية.' where slug = 'infinite-serum-raffermissant';
update products set description_ar = 'الكريم المُصلح، بقوامه الخفيف الناعم، غني بالألوفيرا والمستخلصات النباتية وزيت الجوجوبا وفيتامين B3. يبدو الوجه ممتلئاً بوضوح، مستعيداً شبابه ومرونته.' where slug = 'infinite-creme-reparatrice';
update products set description_ar = 'يحارب مركّب الشد من الداخل علامات التقدم في السن الظاهرة. يحتوي على مستخلص شمّام فرنسي مسجّل ببراءة اختراع، وسيراميدات نباتية، وكولاجين.' where slug = 'infinite-complexe-raffermissant';
update products set description_ar = 'يمنح هذا اللوشن المنعش البشرة إشراقة حقيقية. يُتمّ إزالة المكياج ويخلّص البشرة من آخر الشوائب. غني بالألوفيرا ومستخلص الخيار والشاي الأبيض.' where slug = 'infinite-lotion-tonifiante';
update products set description_ar = 'كريم محيط العين سر نظرة متألقة. يجمع بين الألوفيرا ومستخلص الكولاجين لنظرة أصغر سناً بوضوح، ومستخلص شجرة الحرير لمحو علامات التعب.' where slug = 'infinite-creme-contour-yeux';
update products set description_ar = 'المقشّر هو الحليف المثالي لبشرة جديدة وأكثر نقاءً. تُقشَّر بشرتك وتُنظَّف بعمق بفضل البروميلين والبابايين ولؤلؤ الجوجوبا والخيزران.' where slug = 'infinite-soin-exfoliant';
update products set description_ar = 'اكتشف منشّط الألوة، عناية أساسية يمكن استخدامها وحدها لإتمام إزالة المكياج وترطيب البشرة وتنشيط لونها.' where slug = 'infinite-activateur-aloes';
update products set description_ar = 'يملأ سيروم الترطيب بشرتك ويرطبها بشكل مثالي مع تقليل ظهور الخطوط الدقيقة والتجاعيد بفضل مزيج من 4 أحماض هيالورونيك.' where slug = 'infinite-serum-hydratant';
